services:
  whisper-asr-webservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASR_MODEL=base
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - cache-pip:/root/.cache/pip
      - cache-poetry:/root/.cache/poetry
      - cache-whisper:/root/.cache/whisper
    networks:
      - translationNetwork
volumes:
  cache-pip:
  cache-poetry:
  cache-whisper:
  cache-faster-whisper:
networks:
    translationNetwork:
        external: true